spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.dzjqyet.mongodb.net/e-learning

springdoc:
  packagesToScan: com.elearning.apis
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true

server:
  port: 8080
  servlet:
    context-path: /e-learning
  max-http-header-size: 10MB