spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.dzjqyet.mongodb.net/e-learning
  mail:
    host: smtp.gmail.com
    port: 587
    username: thomsonbel12@gmail.com
    password: alcjlxnqrngukuky
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000

vnpay:
  tmn-code: 2QXUIQX4
  secret_key: ZYJXZQKZQKXZQXZQKXZQXZQKXZQXZQKX
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/v1/payment/vnpay-return
  ipn-url: http://localhost:8080/api/v1/payment/vnpay-ipn